pipeline {
  agent any

  triggers {
    githubPush()
  }

  environment {
    DOCKERHUB_CREDENTIALS = credentials('dockerhub-creds')
    TELEGRAM_BOT_TOKEN = '7964045222:AAElE5m35X1rUfU-2lO0ZpLzwuy_esmMsvY'
    TELEGRAM_CHAT_ID = '1868802578'
  }

  stages {
    stage('Build & Push Frontend') {
      steps {
        dir('fp-frontend-fix') {
          sh 'docker build -t kautsarakasyah/fp-frontend:latest .'
          withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
            sh 'echo $PASS | docker login -u $USER --password-stdin'
            sh 'docker push kautsarakasyah/fp-frontend:latest'
          }
        }
      }
    }

    stage('Deploy to OpenShift') {
      steps {
        sh 'oc rollout restart deployment fp-frontend -n final-app-deployment'
      }
    }
  }

  post {
    success {
      sh "curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage -d chat_id=$TELEGRAM_CHAT_ID -d text='✅ Deploy frontend sukses'"
    }
    failure {
      sh "curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage -d chat_id=$TELEGRAM_CHAT_ID -d text='❌ Deploy frontend gagal'"
    }
  }
}