version: "3"

services:
  gopay-service:
    build: .
    ports:
      - "8080:8080"
    container_name: gopay-service

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true

volumes:
  jenkins_home:
