apiVersion: v1
kind: Service
metadata:
  name: gopay-service
  namespace: final-app-deployment
  labels:
    app: gopay
spec:
  selector:
    app: gopay
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP