global:
  resolve_timeout: 5m

receivers:
  - name: 'telegram'
    telegram_configs:
      - bot_token: '7964045222:AAElE5m35X1rUfU-2lO0ZpLzwuy_esmMsvY'
        chat_id: '1868802578'
        message: "🔥 *{{ .CommonLabels.alertname }}*\n{{ .CommonAnnotations.description }}"
        parse_mode: "Markdown"

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h
  receiver: 'telegram'