apiVersion: v1
kind: Service
metadata:
  name: fp-frontend-service
  namespace: final-app-deployment
  labels:
    app: fp-frontend
spec:
  selector:
    app: fp-frontend
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 9002
  type: ClusterIP