apiVersion: v1
kind: Service
metadata:
  name: bni-postgres
  namespace: final-app-deployment
  labels:
    app: bni-postgres
spec:
  selector:
    app: bni-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP