apiVersion: v1
kind: Secret
metadata:
  name: fp-frontend-secret
  namespace: final-app-deployment
  labels:
    app: final-app
stringData:
  POSTGRES_URL: "postgres://final_project_bni_user:mysecretpassword@bni-postgres:5432/final_project_bni"
  JWT_SECRET: "your-super-secret-jwt-key"
  NEXT_PUBLIC_APP_URL: "http://fp-frontend-service:9002"
  NEXT_PUBLIC_SHOPEEPAY_URL: "http://shopeepay-service:8080"
  NEXT_PUBLIC_GOPAY_URL: "http://gopay-service:8081"